#!/bin/bash
# gets the temperature of all CPU cores usings lm_sensors and averages them

core0=$(sensors | grep 'Core 0' | awk -F ' ' '{print $3}' | awk -F '.' '{print $1}' | cut -c 2-)
core1=$(sensors | grep 'Core 1' | awk -F ' ' '{print $3}' | awk -F '.' '{print $1}' | cut -c 2-)
avg=$((($core0+$core1)/2))
echo $avg
